services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: mcr.microsoft.com/devcontainers/python:3.11-bullseye
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
